version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: linuxserver_jellyfin
    # environment:
      #- PUID=0
      #- PGID=65536
      #- TZ=America/Chicago
      #- JELLYFIN_PublishedServerUrl=<IP> #optional
    volumes:
      - config:/config
      - video:/data/video
      - music:/data/music
    ports:
      - ${JELLYFIN_PUBLISHED_PORT}:8096
    restart: unless-stopped
    network_mode: "host"
volumes:
  config:
  video:
  music: