version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: linuxserver_jellyfin
    # environment:
      #- PUID=1024
      #- PGID=65536
      #- TZ=America/Chicago
      #- JELLYFIN_PublishedServerUrl=<IP> #optional
    volumes:
      - /volume1/docker/jellyfin/config:/config
      - /volume1/video:/data/video
      - /volume1/music:/data/music
    devices:
      - /dev/dri:/dev/dri
    ports:
      - ${JELLYFIN_PUBLISHED_PORT}:8096
    restart: unless-stopped
    network_mode: "host"
